#!/usr/bin/env node
/**
 * Build script: reads all Gemini-generated JSON summaries from src/paperData/
 * and generates src/generatedPaperContent.js with transformed PAPER_CONTENT.
 *
 * Maps Gemini JSON fields → FullContent component expected format:
 *   - epigraph, keyFindings, theorem{formal,plain}, mcResults{beta,ci,dw,pi}
 *   - agents{whistleblower,plaintiff,regulator,legislator,investor,supranational}
 *   - faq[{q,a}]
 *   - NEW: executiveSummary, caseStudies, policyAnalysis, axioms, proofSketch,
 *     welfareChannels, channelTable, monteCarlo, crossDomain, methodology,
 *     timeline, literatureContext
 */

const fs = require("fs");
const path = require("path");

const DATA_DIR = path.join(__dirname, "..", "src", "paperData");
const OUT_FILE = path.join(__dirname, "..", "src", "generatedPaperContent.js");

function slugToKey(slug) {
  // Use slug as-is — buildPaperList looks up by d.id which uses hyphens
  return slug;
}

function transformJson(data) {
  const content = {};

  // Epigraph
  if (data.epigraph) content.epigraph = data.epigraph;

  // Executive summary (new field)
  if (data.executiveSummary) content.executiveSummary = data.executiveSummary;

  // Key findings
  if (data.keyFindings && Array.isArray(data.keyFindings)) {
    content.keyFindings = data.keyFindings;
  }

  // Theorem
  if (data.theorem) {
    content.theorem = {
      formal: data.theorem.formal || "",
      plain: data.theorem.plain || "",
    };
    if (data.theorem.axioms) content.axioms = data.theorem.axioms;
    if (data.theorem.proofSketch) content.proofSketch = data.theorem.proofSketch;
  }

  // MC Results - from welfareAnalysis or direct
  if (data.welfareAnalysis) {
    const wa = data.welfareAnalysis;
    const beta = parseFloat(wa.betaW) || null;
    content.mcResults = {
      beta: beta,
      ci: wa.ci90 || null,
      dw: parseFloat(String(wa.deltaW).replace(/[^0-9.]/g, "")) || null,
      pi: parseFloat(String(wa.pi).replace(/[^0-9.]/g, "")) || null,
    };
    if (wa.channels) content.welfareChannels = wa.channels;
    if (wa.channelTable) content.channelTable = wa.channelTable;
    if (wa.monteCarlo) content.monteCarlo = wa.monteCarlo;
  }

  // Agents - map "insider" → "whistleblower" for backward compat
  if (data.agents) {
    content.agents = {
      whistleblower: data.agents.insider || data.agents.whistleblower || "",
      plaintiff: data.agents.plaintiff || "",
      regulator: data.agents.regulator || "",
      legislator: data.agents.legislator || "",
      investor: data.agents.investor || "",
      supranational: data.agents.supranational || "",
    };
  }

  // FAQ
  if (data.faq && Array.isArray(data.faq)) {
    content.faq = data.faq;
  }

  // Case studies (new field)
  if (data.caseStudies && Array.isArray(data.caseStudies)) {
    content.caseStudies = data.caseStudies;
  }

  // Policy analysis (new field)
  if (data.policyAnalysis) {
    content.policyAnalysis = data.policyAnalysis;
  }

  // Cross-domain connections (new field)
  if (data.crossDomainConnections && Array.isArray(data.crossDomainConnections)) {
    content.crossDomain = data.crossDomainConnections;
  }

  // Methodology (new field)
  if (data.methodology) content.methodology = data.methodology;

  // Timeline (new field)
  if (data.timeline && Array.isArray(data.timeline)) {
    content.timeline = data.timeline;
  }

  // Literature context (new field)
  if (data.literatureContext) content.literatureContext = data.literatureContext;

  return content;
}

// Main
const files = fs.readdirSync(DATA_DIR).filter(f => f.endsWith(".json") && !f.includes("_raw"));
console.log(`Found ${files.length} JSON files in ${DATA_DIR}`);

const contentMap = {};
let ok = 0, fail = 0;

for (const file of files) {
  const slug = file.replace(".json", "");
  const key = slugToKey(slug);
  try {
    const raw = fs.readFileSync(path.join(DATA_DIR, file), "utf-8");
    const data = JSON.parse(raw);
    contentMap[key] = transformJson(data);
    ok++;
  } catch (e) {
    console.error(`  FAIL ${slug}: ${e.message}`);
    fail++;
  }
}

// Generate output
const output = `// AUTO-GENERATED by scripts/build_paper_content.js
// Do not edit manually. Regenerate with: node scripts/build_paper_content.js
// Generated: ${new Date().toISOString()}
// Papers: ${ok} ok, ${fail} failed

export const GENERATED_CONTENT = ${JSON.stringify(contentMap, null, 2)};
`;

fs.writeFileSync(OUT_FILE, output, "utf-8");
console.log(`\nWrote ${OUT_FILE} (${(output.length / 1024 / 1024).toFixed(1)}MB, ${ok} papers)`);
