// Generated from journal_targeting_v2.md (happy homes strategy) + publicationDirectoryData.js
// Updated on 2026-04-24. Publication rank is intended publication order, not manuscript number.
// Journal targets from reference/journal_targeting_v2.md. Econometrica removed per Erik directive 2026-04-24.

export const PUBLICATION_DIRECTORY = {
  "papers": [
    {
      "rank": 1,
      "name": "The Private Pareto Trap: Bilateral Efficiency and System Welfare Cannot Coexist",
      "slug": "ppt",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Done",
      "journal": "Games and Economic Behavior",
      "ssrnUrl": null,
      "webPath": "/papers/ppt/",
      "blocker": null,
      "fallback": "Journal of Economic Theory",
      "expectedPubDate": "2027 Q1"
    },
    {
      "rank": 2,
      "name": "The Disclosure Futility Theorem: Why Information Cannot Fix a Structural Game",
      "slug": "disclosure-futility",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Done",
      "journal": "Journal of Economic Theory",
      "ssrnUrl": null,
      "webPath": "/papers/disclosure-futility/",
      "blocker": null,
      "fallback": "Games and Economic Behavior",
      "expectedPubDate": "2027 Q1"
    },
    {
      "rank": 3,
      "name": "Game-Change / Institutional Transformation: Rule Changes and Equilibrium Escape",
      "slug": "conflictoring",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Done",
      "journal": "Games and Economic Behavior",
      "ssrnUrl": null,
      "webPath": "/papers/conflictoring/",
      "blocker": null,
      "fallback": "Journal of Economic Theory",
      "expectedPubDate": "2027 Q1"
    },
    {
      "rank": 4,
      "name": "Accountability Reconstruction: Decision Records in Personal-Liability Regimes",
      "slug": "accountability-reconstruction",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Drafting",
      "journal": "Journal of Law, Economics, and Organization",
      "ssrnUrl": null,
      "webPath": "/papers/accountability-reconstruction/",
      "blocker": "New fourth theory paper; requires journal-length voice, legal-source verification, and cross-corpus propagation",
      "fallback": "Journal of Legal Studies",
      "expectedPubDate": "2027 Q2"
    },
    {
      "rank": 5,
      "name": "General Equilibrium Properties of Process Disclosure: Five Theorems on Governance Documentation",
      "slug": "da-1",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Done",
      "journal": "SSRN Working Paper",
      "ssrnUrl": null,
      "webPath": "/papers/da-1/",
      "blocker": "Long SSRN master paper; journal submission requires DA2-DA5 split and appendix architecture",
      "fallback": null,
      "expectedPubDate": "Split → DA-2 through DA-5"
    },
    {
      "rank": 6,
      "name": "The Fiscal Capture Theorem: Why Governments Cannot Reform What They Depend On",
      "slug": "fiscal-capture",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Done",
      "journal": "Journal of Public Economics",
      "ssrnUrl": null,
      "webPath": "/papers/fiscal-capture/",
      "blocker": null,
      "fallback": "AEJ: Economic Policy",
      "expectedPubDate": "2027 Q1"
    },
    {
      "rank": 7,
      "name": "The Reform Dividend",
      "slug": "reform-dividend",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Done",
      "journal": "Review of Economics and Statistics",
      "ssrnUrl": null,
      "webPath": "/papers/reform-dividend/",
      "blocker": null,
      "fallback": "Journal of Public Economics",
      "expectedPubDate": "2027 Q2"
    },
    {
      "rank": 8,
      "name": "Postnieks's Law: Private Markets Cannot Price What They Collectively Destroy",
      "slug": "postnieks-law",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Done",
      "journal": "Journal of Public Economics",
      "ssrnUrl": null,
      "webPath": "/papers/postnieks-law/",
      "blocker": null,
      "fallback": "Review of Economics and Statistics",
      "expectedPubDate": "2027 Q1"
    },
    {
      "rank": 9,
      "name": "The Substitution Trap Law: Why Regulated Industries Innovate Around Constraints Without Reducing Harm",
      "slug": "substitution-trap",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Done",
      "journal": "Journal of Economic Theory",
      "ssrnUrl": null,
      "webPath": "/papers/substitution-trap/",
      "blocker": null,
      "fallback": "Games and Economic Behavior",
      "expectedPubDate": "2027 Q2"
    },
    {
      "rank": 10,
      "name": "Incomplete Contracts Under Stakeholder Welfare: A General Framework",
      "slug": "hart-stakeholder-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Institutional Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "fallback": "Journal of Law, Economics, and Organization",
      "expectedPubDate": "2027 Q2"
    },
    {
      "rank": 11,
      "name": "The Functional Convergence Theorem: When Corporate Legal Systems Must Converge to Shareholder Primacy and When They Must Not",
      "slug": "kraakman-functional-convergence",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Law, Economics, and Organization",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "fallback": "Journal of Legal Studies",
      "expectedPubDate": "2027 Q2"
    },
    {
      "rank": 12,
      "name": "When Shared Value Is Shared and When It Is Not: A Unified Welfare Theorem for Firm–System Strategy",
      "slug": "porter-shared-value-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Institutional Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "fallback": "Regulation and Governance",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 13,
      "name": "Applying the System Asset Pricing Model to Proof-of-Stake Blockchains: A Cross-Chain Welfare Comparison",
      "slug": "pos",
      "kind": "SAPM",
      "category": "Institutional",
      "status": "Done",
      "journal": "Journal of Financial Regulation",
      "ssrnUrl": null,
      "webPath": "/papers/pos/",
      "blocker": null,
      "fallback": "Energy Economics",
      "expectedPubDate": "2027 Q2"
    },
    {
      "rank": 14,
      "name": "Applying the System Asset Pricing Model to Private Military Contractors: Measuring the System Welfare Cost of Privatized Warfare",
      "slug": "private-military",
      "kind": "SAPM",
      "category": "Jurisdictional / Legal",
      "status": "Done",
      "journal": "Journal of Conflict Resolution",
      "ssrnUrl": null,
      "webPath": "/papers/private-military/",
      "blocker": null,
      "fallback": "Security Dialogue",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 15,
      "name": "Applying the System Asset Pricing Model to Private Prisons and the Carceral State: Measuring the System Welfare Cost of For-Profit Incarceration",
      "slug": "private-prisons",
      "kind": "SAPM",
      "category": "Institutional",
      "status": "Done",
      "journal": "Criminology and Public Policy",
      "ssrnUrl": null,
      "webPath": "/papers/private-prisons/",
      "blocker": null,
      "fallback": "Justice Quarterly",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 16,
      "name": "A Robust-Expectations Welfare Theorem: Model Ambiguity, Bilateral Policy Rules, and the Third-Class Welfare Wedge",
      "slug": "sargent-rational-expectations",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Review of Economics and Statistics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "fallback": "Journal of Monetary Economics",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 17,
      "name": "The Legitimacy Feedback in Capitalist Systems: Surplus Concentration, Institutional Decay, and the Two Steady States of Market Capitalism",
      "slug": "zingales-legitimacy-feedback",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Institutional Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "fallback": "Regulation and Governance",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 18,
      "name": "Applying the System Asset Pricing Model to US Civilian Firearms: Measuring the System Welfare Cost of Lethality-by-Design",
      "slug": "firearms",
      "kind": "SAPM",
      "category": "Constitutional / Institutional",
      "status": "Done",
      "journal": "Journal of Policy Analysis and Management",
      "ssrnUrl": null,
      "webPath": "/papers/firearms/",
      "blocker": null,
      "fallback": "American Journal of Public Health",
      "expectedPubDate": "2027 Q2"
    },
    {
      "rank": 19,
      "name": "Applying the System Asset Pricing Model to Industrial Animal Agriculture: Measuring the System Welfare Cost of Factory Farming",
      "slug": "factory-farming",
      "kind": "SAPM",
      "category": "Biological / Thermodynamic",
      "status": "Done",
      "journal": "Food Policy",
      "ssrnUrl": null,
      "webPath": "/papers/factory-farming/",
      "blocker": null,
      "fallback": "Ecological Economics",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 20,
      "name": "Applying the System Asset Pricing Model to Frontier AI: Measuring the System Welfare Cost of the Capability-Safety Gap",
      "slug": "frontier-ai",
      "kind": "SAPM",
      "category": "Computational / Institutional",
      "status": "Done",
      "journal": "AI and Society",
      "ssrnUrl": null,
      "webPath": "/papers/frontier-ai/",
      "blocker": null,
      "fallback": "Policy and Internet",
      "expectedPubDate": "2027 Q2"
    },
    {
      "rank": 21,
      "name": "Applying the System Asset Pricing Model to Antimicrobial Resistance: The Efficacy Ceiling and the System Welfare Cost of Antibiotic Depletion",
      "slug": "amr",
      "kind": "SAPM",
      "category": "Biological / Evolutionary",
      "status": "Done",
      "journal": "Health Affairs",
      "ssrnUrl": null,
      "webPath": "/papers/amr/",
      "blocker": null,
      "fallback": "PLOS Medicine",
      "expectedPubDate": "2027 Q2"
    },
    {
      "rank": 22,
      "name": "Applying the System Asset Pricing Model to Platform Monopoly: Measuring the System Welfare Cost of Big Tech Acquisitions and Gatekeeper Rent Extraction",
      "slug": "big-tech",
      "kind": "SAPM",
      "category": "Institutional",
      "status": "Done",
      "journal": "Journal of Industrial Economics",
      "ssrnUrl": null,
      "webPath": "/papers/big-tech/",
      "blocker": null,
      "fallback": "Antitrust Law Journal",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 23,
      "name": "Applying the System Asset Pricing Model to Data Brokerage: Measuring the System Welfare Cost of Behavioral Surplus Extraction",
      "slug": "data-brokerage",
      "kind": "SAPM",
      "category": "Informational / Institutional",
      "status": "Done",
      "journal": "Journal of Information Policy",
      "ssrnUrl": null,
      "webPath": "/papers/data-brokerage/",
      "blocker": null,
      "fallback": "Policy and Internet",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 24,
      "name": "Applying the System Asset Pricing Model to Cybercrime: Measuring the System Welfare Cost of the Global Digital Extraction Economy",
      "slug": "cybercrime",
      "kind": "SAPM",
      "category": "Computational / Jurisdictional",
      "status": "Done",
      "journal": "Journal of Cybersecurity",
      "ssrnUrl": null,
      "webPath": "/papers/cybercrime/",
      "blocker": null,
      "fallback": "Computers and Security",
      "expectedPubDate": "2027 Q2"
    },
    {
      "rank": 25,
      "name": "Applying the System Asset Pricing Model to Platform Monopoly: Measuring the System Welfare Cost of Big Tech Acquisitions and Gatekeeper Rent Extraction",
      "slug": "platform-monopoly",
      "kind": "SAPM",
      "category": "Institutional",
      "status": "Done",
      "journal": "Journal of Industrial Economics",
      "ssrnUrl": null,
      "webPath": "/papers/platform-monopoly/",
      "blocker": null,
      "fallback": "Journal of Competition Law and Economics",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 26,
      "name": "Bitcoin: A System Asset Pricing Model and the Protocol Welfare Floor",
      "slug": "bitcoin",
      "kind": "SAPM",
      "category": "Institutional",
      "status": "Done",
      "journal": "Energy Economics",
      "ssrnUrl": null,
      "webPath": "/papers/bitcoin/",
      "blocker": null,
      "fallback": "Resource and Energy Economics",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 27,
      "name": "Applying the System Asset Pricing Model to Alcohol: Measuring the System Welfare Cost of Ethanol Commercialization",
      "slug": "alcohol",
      "kind": "SAPM",
      "category": "Neurochemical / Institutional",
      "status": "Done",
      "journal": "Drug and Alcohol Dependence",
      "ssrnUrl": null,
      "webPath": "/papers/alcohol/",
      "blocker": null,
      "fallback": "Journal of Health Economics",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 28,
      "name": "Applying the System Asset Pricing Model to the Opioid Ecosystem: Measuring the System Welfare Cost of Pharmaceutical-Industrial Regulatory Capture",
      "slug": "opioids",
      "kind": "SAPM",
      "category": "Neurochemical / Institutional",
      "status": "Done",
      "journal": "Health Affairs",
      "ssrnUrl": null,
      "webPath": "/papers/opioids/",
      "blocker": null,
      "fallback": "Drug and Alcohol Dependence",
      "expectedPubDate": "2027 Q2"
    },
    {
      "rank": 29,
      "name": "Applying the System Asset Pricing Model to Human Trafficking: Measuring the System Welfare Cost of the Global Exploitation Premium",
      "slug": "human-trafficking",
      "kind": "SAPM",
      "category": "Jurisdictional / Economic",
      "status": "Done",
      "journal": "Journal of Human Trafficking",
      "ssrnUrl": null,
      "webPath": "/papers/human-trafficking/",
      "blocker": null,
      "fallback": "Journal of Development Economics",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 30,
      "name": "Applying the System Asset Pricing Model to Global Supply Chain Child Labor: Measuring the System Welfare Cost of Exploitative Labor Extraction",
      "slug": "child-labor",
      "kind": "SAPM",
      "category": "Economic / Jurisdictional",
      "status": "Done",
      "journal": "World Development",
      "ssrnUrl": null,
      "webPath": "/papers/child-labor/",
      "blocker": null,
      "fallback": "Journal of Development Economics",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 31,
      "name": "Applying the System Asset Pricing Model to the Global Illicit Drug Trade: Measuring the System Welfare Cost of Prohibition",
      "slug": "illicit-drugs",
      "kind": "SAPM",
      "category": "Institutional / Economic",
      "status": "Done",
      "journal": "International Journal of Drug Policy",
      "ssrnUrl": null,
      "webPath": "/papers/illicit-drugs/",
      "blocker": null,
      "fallback": "Drug and Alcohol Dependence",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 32,
      "name": "Tobacco: A System Asset Pricing Model - Measuring the System Welfare Cost of Combustible Nicotine Addiction",
      "slug": "tobacco",
      "kind": "SAPM",
      "category": "Institutional / Neurochemical",
      "status": "Done",
      "journal": "Tobacco Control",
      "ssrnUrl": null,
      "webPath": "/papers/tobacco/",
      "blocker": null,
      "fallback": "Addiction",
      "expectedPubDate": "2027 Q2"
    },
    {
      "rank": 33,
      "name": "Applying the System Asset Pricing Model to Molecular Persistence: Measuring the System Welfare Cost of PFAS, Microplastics, and Persistent Organic Pollutants",
      "slug": "pfas",
      "kind": "SAPM",
      "category": "Thermodynamic",
      "status": "Done",
      "journal": "Environmental Health Perspectives",
      "ssrnUrl": null,
      "webPath": "/papers/pfas/",
      "blocker": null,
      "fallback": "Environmental Science and Technology",
      "expectedPubDate": "2027 Q2"
    },
    {
      "rank": 34,
      "name": "Applying the System Asset Pricing Model to Ecological Irreversibility: Measuring the System Welfare Cost of Gene Drive Deployment",
      "slug": "gene-drives",
      "kind": "SAPM",
      "category": "Biological / Evolutionary",
      "status": "Done",
      "journal": "Nature Biotechnology",
      "ssrnUrl": null,
      "webPath": "/papers/gene-drives/",
      "blocker": null,
      "fallback": "Biological Conservation",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 35,
      "name": "Applying the System Asset Pricing Model to Conflict Minerals: Measuring the System Welfare Cost of the Global 3TG and Cobalt Supply Chain",
      "slug": "conflict-minerals",
      "kind": "SAPM",
      "category": "Physical / Jurisdictional",
      "status": "Done",
      "journal": "World Development",
      "ssrnUrl": null,
      "webPath": "/papers/conflict-minerals/",
      "blocker": null,
      "fallback": "Resources Policy",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 36,
      "name": "Applying the System Asset Pricing Model to Abyssal Extraction: Measuring the System Welfare Cost of Deep-Sea Polymetallic Nodule Mining",
      "slug": "deep-sea-mining",
      "kind": "SAPM",
      "category": "Geochemical / Physical",
      "status": "Done",
      "journal": "Marine Policy",
      "ssrnUrl": null,
      "webPath": "/papers/deep-sea-mining/",
      "blocker": null,
      "fallback": "Ocean and Coastal Management",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 37,
      "name": "Applying the System Asset Pricing Model to Deforestation and Logging: Measuring the System Welfare Cost of Tropical Forest Liquidation",
      "slug": "deforestation",
      "kind": "SAPM",
      "category": "Biological / Temporal",
      "status": "Done",
      "journal": "Journal of Environmental Economics and Management",
      "ssrnUrl": null,
      "webPath": "/papers/deforestation/",
      "blocker": null,
      "fallback": "Forest Policy and Economics",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 38,
      "name": "Applying the System Asset Pricing Model to Fossil Fuels: Measuring the System Welfare Cost of Global Oil and Gas Extraction",
      "slug": "oil-gas",
      "kind": "SAPM",
      "category": "Thermodynamic",
      "status": "Done",
      "journal": "Energy Policy",
      "ssrnUrl": null,
      "webPath": "/papers/oil-gas/",
      "blocker": null,
      "fallback": "Energy Economics",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 39,
      "name": "Applying the System Asset Pricing Model to Global Coal Combustion: Measuring the System Welfare Cost of Non-Essential Thermal Coal Revenue",
      "slug": "coal",
      "kind": "SAPM",
      "category": "Thermodynamic",
      "status": "Done",
      "journal": "Energy Policy",
      "ssrnUrl": null,
      "webPath": "/papers/coal/",
      "blocker": null,
      "fallback": "Energy Economics",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 40,
      "name": "Applying the System Asset Pricing Model to Mining and Rare Earth Extraction: Measuring the System Welfare Cost of Critical Mineral Supply Chains",
      "slug": "mining-rare-earth",
      "kind": "SAPM",
      "category": "Geochemical",
      "status": "Done",
      "journal": "Resources Policy",
      "ssrnUrl": null,
      "webPath": "/papers/mining-rare-earth/",
      "blocker": null,
      "fallback": "Extractive Industries and Society",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 41,
      "name": "Applying the System Asset Pricing Model to Credit Rating Agencies: Measuring the System Welfare Cost of the Issuer-Pays Oligopoly",
      "slug": "credit-rating",
      "kind": "SAPM",
      "category": "Institutional / Informational",
      "status": "Done",
      "journal": "Journal of Banking and Finance",
      "ssrnUrl": null,
      "webPath": "/papers/credit-rating/",
      "blocker": null,
      "fallback": "Journal of Financial Stability",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 42,
      "name": "Applying the System Asset Pricing Model to the Attention Economy: Measuring the System Welfare Cost of Algorithmic Engagement Maximization Targeting Youth",
      "slug": "social-media",
      "kind": "SAPM",
      "category": "Computational / Developmental",
      "status": "Done",
      "journal": "New Media and Society",
      "ssrnUrl": null,
      "webPath": "/papers/social-media/",
      "blocker": null,
      "fallback": "Journal of Youth and Adolescence",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 43,
      "name": "Applying the System Asset Pricing Model to Sovereign Debt: Measuring the System Welfare Cost of Intergenerational Fiscal Extraction",
      "slug": "sovereign-debt",
      "kind": "SAPM",
      "category": "Institutional / Temporal",
      "status": "Done",
      "journal": "Journal of International Economics",
      "ssrnUrl": null,
      "webPath": "/papers/sovereign-debt/",
      "blocker": null,
      "fallback": "IMF Economic Review",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 44,
      "name": "Applying the System Asset Pricing Model to Student Loan Securitization and For-Profit Education: Measuring the System Welfare Cost of Financialized Human Capital Extraction",
      "slug": "student-loans",
      "kind": "SAPM",
      "category": "Institutional / Financial",
      "status": "Done",
      "journal": "Economics of Education Review",
      "ssrnUrl": null,
      "webPath": "/papers/student-loans/",
      "blocker": null,
      "fallback": "Journal of Higher Education",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 45,
      "name": "Applying the System Asset Pricing Model to Tax Havens: Measuring the System Welfare Cost of Offshore Profit Shifting",
      "slug": "tax-havens",
      "kind": "SAPM",
      "category": "Jurisdictional / Institutional",
      "status": "Done",
      "journal": "Journal of Public Economics",
      "ssrnUrl": null,
      "webPath": "/papers/tax-havens/",
      "blocker": null,
      "fallback": "Fiscal Studies",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 46,
      "name": "Applying the System Asset Pricing Model to Water Privatization and Aquifer Depletion: Measuring the System Welfare Cost of Commodifying a Common-Pool Resource",
      "slug": "water-privatization",
      "kind": "SAPM",
      "category": "Hydrogeological / Institutional",
      "status": "Done",
      "journal": "World Development",
      "ssrnUrl": null,
      "webPath": "/papers/water-privatization/",
      "blocker": null,
      "fallback": "Utilities Policy",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 47,
      "name": "Applying the System Asset Pricing Model to Electronic Waste: Measuring the System Welfare Cost of Planned Obsolescence and Toxic Externalization",
      "slug": "ewaste",
      "kind": "SAPM",
      "category": "Jurisdictional / Classification",
      "status": "Done",
      "journal": "Resources, Conservation and Recycling",
      "ssrnUrl": null,
      "webPath": "/papers/ewaste/",
      "blocker": null,
      "fallback": "Waste Management",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 48,
      "name": "Applying the System Asset Pricing Model to Plastics: Measuring the System Welfare Cost of Synthetic Polymer Proliferation",
      "slug": "plastics",
      "kind": "SAPM",
      "category": "Thermodynamic",
      "status": "Done",
      "journal": "Environmental Science and Technology",
      "ssrnUrl": null,
      "webPath": "/papers/plastics/",
      "blocker": null,
      "fallback": "Marine Pollution Bulletin",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 49,
      "name": "Applying the System Asset Pricing Model to Industrial Agriculture: Measuring the System Welfare Cost of Methane-Intensive Livestock Production",
      "slug": "industrial-ag-methane",
      "kind": "SAPM",
      "category": "Thermodynamic / Biological",
      "status": "Done",
      "journal": "Environmental and Resource Economics",
      "ssrnUrl": null,
      "webPath": "/papers/industrial-ag-methane/",
      "blocker": null,
      "fallback": "Agricultural Systems",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 50,
      "name": "Applying the System Asset Pricing Model to Palm Oil: Measuring the System Welfare Cost of Tropical Commodity Extraction",
      "slug": "palm-oil",
      "kind": "SAPM",
      "category": "Biological / Agricultural",
      "status": "Done",
      "journal": "Forest Policy and Economics",
      "ssrnUrl": null,
      "webPath": "/papers/palm-oil/",
      "blocker": null,
      "fallback": "Land Use Policy",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 51,
      "name": "Applying the System Asset Pricing Model to Global Maritime Shipping: Measuring the System Welfare Cost of Unpriced Externalities in the World's Trade Backbone",
      "slug": "shipping",
      "kind": "SAPM",
      "category": "Jurisdictional / Physical",
      "status": "Done",
      "journal": "Maritime Policy and Management",
      "ssrnUrl": null,
      "webPath": "/papers/shipping/",
      "blocker": null,
      "fallback": "Transport Reviews",
      "expectedPubDate": "2027 Q4"
    },
    {
      "rank": 52,
      "name": "Applying the System Asset Pricing Model to Commercial Aviation: Measuring the System Welfare Cost of Unpriced Atmospheric Externalities",
      "slug": "aviation",
      "kind": "SAPM",
      "category": "Physical / Thermodynamic",
      "status": "Done",
      "journal": "Transport Policy",
      "ssrnUrl": null,
      "webPath": "/papers/aviation/",
      "blocker": null,
      "fallback": "Transportation Research Part D",
      "expectedPubDate": "2027 Q4"
    },
    {
      "rank": 53,
      "name": "Applying the System Asset Pricing Model to Cement and Concrete Production: Measuring the System Welfare Cost of Calcination Lock-In",
      "slug": "cement",
      "kind": "SAPM",
      "category": "Thermodynamic",
      "status": "Done",
      "journal": "Journal of Industrial Ecology",
      "ssrnUrl": null,
      "webPath": "/papers/cement/",
      "blocker": null,
      "fallback": "Journal of Cleaner Production",
      "expectedPubDate": "2027 Q4"
    },
    {
      "rank": 54,
      "name": "Applying the System Asset Pricing Model to Fast Fashion: Measuring the System Welfare Cost of Planned Disposability",
      "slug": "fast-fashion",
      "kind": "SAPM",
      "category": "Thermodynamic / Temporal",
      "status": "Done",
      "journal": "Journal of Cleaner Production",
      "ssrnUrl": null,
      "webPath": "/papers/fast-fashion/",
      "blocker": null,
      "fallback": "Sustainability",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 55,
      "name": "Applying the System Asset Pricing Model to Algorithmic Pricing: Measuring the System Welfare Cost of Coordinated Surplus Extraction",
      "slug": "algorithmic-pricing",
      "kind": "SAPM",
      "category": "Computational / Legal",
      "status": "Done",
      "journal": "Journal of Industrial Economics",
      "ssrnUrl": null,
      "webPath": "/papers/algorithmic-pricing/",
      "blocker": null,
      "fallback": "Journal of Competition Law and Economics",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 56,
      "name": "Applying the System Asset Pricing Model to Pharmacy Benefit Management: Measuring the System Welfare Cost of the U.S. Rebate Intermediary",
      "slug": "pbm",
      "kind": "SAPM",
      "category": "Institutional / Financial",
      "status": "Done",
      "journal": "Journal of Health Economics",
      "ssrnUrl": null,
      "webPath": "/papers/pbm/",
      "blocker": null,
      "fallback": "Health Affairs",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 57,
      "name": "Applying the System Asset Pricing Model to Private Equity in Healthcare: Measuring the System Welfare Cost of Financial Extraction from Essential Medical Infrastructure",
      "slug": "pe-healthcare",
      "kind": "SAPM",
      "category": "Institutional",
      "status": "Done",
      "journal": "Journal of Health Economics",
      "ssrnUrl": null,
      "webPath": "/papers/pe-healthcare/",
      "blocker": null,
      "fallback": "Health Affairs",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 58,
      "name": "Applying the System Asset Pricing Model to Commercial Gambling: Measuring the System Welfare Cost of Predatory Extraction",
      "slug": "gambling",
      "kind": "SAPM",
      "category": "Institutional / Neurochemical",
      "status": "Done",
      "journal": "Journal of Gambling Studies",
      "ssrnUrl": null,
      "webPath": "/papers/gambling/",
      "blocker": null,
      "fallback": "Addiction",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 59,
      "name": "The Self-Referential Pricing Trap: FX-Fixing, Benchmark Governance, and the Welfare Cost of Index-Embedded Markets",
      "slug": "fx-fixing",
      "kind": "SAPM",
      "category": "Institutional / Informational",
      "status": "Done",
      "journal": "Journal of Financial Regulation",
      "ssrnUrl": null,
      "webPath": "/papers/fx-fixing/",
      "blocker": null,
      "fallback": "Journal of Banking and Finance",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 60,
      "name": "Applying the System Asset Pricing Model to Commercial Real Estate: Measuring the System Welfare Cost of the Office Vacancy Crisis and Urban Hollowing",
      "slug": "cre",
      "kind": "SAPM",
      "category": "Institutional / Financial",
      "status": "Done",
      "journal": "Journal of Real Estate Finance and Economics",
      "ssrnUrl": null,
      "webPath": "/papers/cre/",
      "blocker": null,
      "fallback": "Real Estate Economics",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 61,
      "name": "Applying the System Asset Pricing Model to Insurance and Climate Risk: Measuring the System Welfare Cost of Climate Risk Mispricing",
      "slug": "insurance-climate",
      "kind": "SAPM",
      "category": "Institutional / Temporal",
      "status": "Done",
      "journal": "Journal of Risk and Insurance",
      "ssrnUrl": null,
      "webPath": "/papers/insurance-climate/",
      "blocker": null,
      "fallback": "Geneva Risk and Insurance Review",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 62,
      "name": "Applying the System Asset Pricing Model to Global Fisheries: Measuring the System Welfare Cost of Ocean Depletion",
      "slug": "fisheries",
      "kind": "SAPM",
      "category": "Climate / Jurisdictional",
      "status": "Done",
      "journal": "Marine Policy",
      "ssrnUrl": null,
      "webPath": "/papers/fisheries/",
      "blocker": null,
      "fallback": "Fish and Fisheries",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 63,
      "name": "Applying the System Asset Pricing Model to International Arms Exports: Measuring the System Welfare Cost of Legitimate Arms Transfers",
      "slug": "arms-exports",
      "kind": "SAPM",
      "category": "Institutional / Jurisdictional",
      "status": "Done",
      "journal": "Journal of Peace Research",
      "ssrnUrl": null,
      "webPath": "/papers/arms-exports/",
      "blocker": null,
      "fallback": "Defence and Peace Economics",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 64,
      "name": "Applying the System Asset Pricing Model to Cryptocurrency Stablecoins: Measuring the System Welfare Cost of Crypto Shadow Banking",
      "slug": "stablecoins",
      "kind": "SAPM",
      "category": "Institutional / Financial",
      "status": "Done",
      "journal": "Journal of Financial Regulation",
      "ssrnUrl": null,
      "webPath": "/papers/stablecoins/",
      "blocker": null,
      "fallback": "Journal of Financial Stability",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 65,
      "name": "Applying the System Asset Pricing Model to Pedospheric Depletion: Measuring the System Welfare Cost of Global Topsoil Erosion",
      "slug": "topsoil",
      "kind": "SAPM",
      "category": "Geochemical",
      "status": "Done",
      "journal": "Land Degradation and Development",
      "ssrnUrl": null,
      "webPath": "/papers/topsoil/",
      "blocker": null,
      "fallback": "Soil and Tillage Research",
      "expectedPubDate": "2027 Q4"
    },
    {
      "rank": 66,
      "name": "Applying the System Asset Pricing Model to Ultra-Processed Food: Measuring the System Welfare Cost of Engineered Dietary Harm",
      "slug": "upf",
      "kind": "SAPM",
      "category": "Neurochemical / Institutional",
      "status": "Done",
      "journal": "Food Policy",
      "ssrnUrl": null,
      "webPath": "/papers/upf/",
      "blocker": null,
      "fallback": "Public Health Nutrition",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 67,
      "name": "Applying the System Asset Pricing Model to Groundwater Depletion: Measuring the System Welfare Cost of Ogallala Aquifer Mining",
      "slug": "groundwater",
      "kind": "SAPM",
      "category": "Hydrogeological / Institutional",
      "status": "Done",
      "journal": "Water Resources Research",
      "ssrnUrl": null,
      "webPath": "/papers/groundwater/",
      "blocker": null,
      "fallback": "Hydrogeology Journal",
      "expectedPubDate": "2027 Q4"
    },
    {
      "rank": 68,
      "name": "Applying the System Asset Pricing Model to Predatory Consumer Lending: Measuring the System Welfare Cost of the Payday Debt Trap",
      "slug": "payday-lending",
      "kind": "SAPM",
      "category": "Financial / Institutional",
      "status": "Done",
      "journal": "Journal of Consumer Affairs",
      "ssrnUrl": null,
      "webPath": "/papers/payday-lending/",
      "blocker": null,
      "fallback": "Journal of Financial Services Research",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 69,
      "name": "Applying the System Asset Pricing Model to Persistent Organic Pollutants Beyond PFAS: Measuring the System Welfare Cost of Legacy Chemical Persistence",
      "slug": "pops",
      "kind": "SAPM",
      "category": "Thermodynamic / Chemical",
      "status": "Done",
      "journal": "Environmental Health Perspectives",
      "ssrnUrl": null,
      "webPath": "/papers/pops/",
      "blocker": null,
      "fallback": "Chemosphere",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 70,
      "name": "Applying the System Asset Pricing Model to Genetic Uniformity: Measuring the System Welfare Cost of Global Monoculture Agriculture",
      "slug": "monoculture",
      "kind": "SAPM",
      "category": "Biological / Evolutionary",
      "status": "Done",
      "journal": "Ecological Economics",
      "ssrnUrl": null,
      "webPath": "/papers/monoculture/",
      "blocker": null,
      "fallback": "Agriculture, Ecosystems and Environment",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 71,
      "name": "Applying the System Asset Pricing Model to Orbital Access: Measuring the System Welfare Cost of Low Earth Orbit Congestion",
      "slug": "orbital-debris",
      "kind": "SAPM",
      "category": "Physical / Jurisdictional",
      "status": "Done",
      "journal": "Space Policy",
      "ssrnUrl": null,
      "webPath": "/papers/orbital-debris/",
      "blocker": null,
      "fallback": "Journal of Space Safety Engineering",
      "expectedPubDate": "2027 Q4"
    },
    {
      "rank": 72,
      "name": "Applying the System Asset Pricing Model to U.S. Defense Procurement: Measuring the System Welfare Cost of Monopoly Rent and Structural Inefficiency",
      "slug": "defense-procurement",
      "kind": "SAPM",
      "category": "Institutional / Political",
      "status": "Done",
      "journal": "Defence and Peace Economics",
      "ssrnUrl": null,
      "webPath": "/papers/defense-procurement/",
      "blocker": null,
      "fallback": "Journal of Defense Modeling and Simulation",
      "expectedPubDate": "2027 Q4"
    },
    {
      "rank": 73,
      "name": "Applying the System Asset Pricing Model to WMD Capability Diffusion: Measuring the System Welfare Cost of Weapons of Mass Destruction Proliferation",
      "slug": "wmd",
      "kind": "SAPM",
      "category": "Informational",
      "status": "Done",
      "journal": "Journal of Conflict Resolution",
      "ssrnUrl": null,
      "webPath": "/papers/wmd/",
      "blocker": null,
      "fallback": "Nonproliferation Review",
      "expectedPubDate": "2027 Q3"
    },
    {
      "rank": 74,
      "name": "Bilateral Efficiency and the Excluded Community: A Structural Welfare Theorem in New Trade Theory and Economic Geography",
      "slug": "krugman-trade-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "World Economy",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 75,
      "name": "The Hollow Win of Trade Liberalization: Heterogeneous Firms, Bilateral Gains, and the Structurally Excluded Welfare of the Exit Margin",
      "slug": "melitz-heterogeneous-firms-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of International Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 76,
      "name": "Interpretable Causal Machine Learning for Policy Evaluation: A Unified Identification-Heterogeneity-Welfare Framework",
      "slug": "imbens-heterogeneous-treatment",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Econometrics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 77,
      "name": "A General Welfare Theorem for Labor Markets Under Imperfect Competition",
      "slug": "card-labor-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Labor Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 78,
      "name": "When Politics Dominates Efficiency: A General Theorem of Corporate Governance Path Dependence, a Unified Measurement Framework for Short-Termism, and the Missing Welfare Dimension",
      "slug": "roe-political-governance-theorem",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Columbia Law Review",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 79,
      "name": "Welfare Decomposition in Heterogeneous-Response Policy Evaluation: A Unified Framework",
      "slug": "heckman-welfare-decomposition",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "To be determined",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 80,
      "name": "The Regulatory Cycle in Corporate Governance: A Welfare-Weighted Theorem of Federal-State Allocation",
      "slug": "romano-regulatory-cycle",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Stanford Law Review",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 81,
      "name": "A Unified Welfare Theorem for Behavioral Markets: Planner-Doer Architecture, Nine Anomaly Mappings, and the Irreducible Floor",
      "slug": "thaler-behavioral-welfare-unification",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Economic Behavior & Organization",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 82,
      "name": "Governance Form Evolution Under Institutional Decay: A Dynamic Extension of Transaction Cost Economics",
      "slug": "williamson-governance-evolution",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Law, Economics, and Organization",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 83,
      "name": "Legal Origins Dynamics: A Theorem of Institutional Transition",
      "slug": "shleifer-legal-origins-dynamics",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Law and Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 84,
      "name": "The Instrumental Variables Welfare Theorem: Local Average Treatment Effects, Non-Complier Welfare, and the Limits of Causal Identification for Policy",
      "slug": "angrist-labor-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Review of Economics and Statistics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 85,
      "name": "Bilateral Elegance, System Silence: A Welfare Completion Theorem for Venture Capital Governance",
      "slug": "gilson-venture-governance-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Review of Financial Studies",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 86,
      "name": "A Unified Platform Welfare Theorem: Two-Sided Markets, Regulatory Capture, and Behavioral Users",
      "slug": "tirole-platform-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Rand Journal of Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 87,
      "name": "The Offshore Wealth Welfare Completion Theorem: Why Bilateral Taxpayer–Jurisdiction Bargains Cannot Price Invisible Base",
      "slug": "zucman-hidden-wealth-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Public Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 88,
      "name": "The Tax Base Visibility Welfare Completion Theorem: Optimal Taxation When the Base Is Endogenous",
      "slug": "saez-optimal-taxation-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Review of Economic Studies",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 89,
      "name": "The Bounded Rationality Welfare Theorem: Satisficing, Aspiration Levels, and the Structural Exclusion of System Welfare",
      "slug": "cyert-simon-behavioral-firm",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Administrative Science Quarterly",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 90,
      "name": "The Systemic Externality Completion Theorem: Welfare Pricing of Fire Sales, Runs, and the Fiscal Backstop in Macro-Finance",
      "slug": "brunnermeier-systemic-risk-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Monetary Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 91,
      "name": "The Gatekeeper Failure Theorem: Reputational Intermediaries, Capture Conditions, and the Structural Case for Decision Accounting",
      "slug": "coffee-gatekeeper-failure",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Columbia Law Review",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 92,
      "name": "The Trilemma Welfare Completion Theorem: When Bilateral Policy Bargains Price Efficiency and Distribution but Not Deliberative Capacity",
      "slug": "rodrik-policy-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Economic Perspectives",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 93,
      "name": "The Passive Ownership Accountability Void: A General Theorem of Concentrated Passive Ownership with Fiduciary Duty Decay",
      "slug": "bebchuk-passive-ownership",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Law and Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 94,
      "name": "The Property Rights Welfare Theorem: Residual Control, Asset Ownership, and the Systematic Exclusion of Non-Contracting Parties",
      "slug": "grossman-hart",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Political Economy",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 95,
      "name": "PK\u0003\u0004\u0014\u0000\u0000\u0000\b\u0000W��\\>�\u0010��\u0001\u0000\u0000b\b\u0000\u0000\u0013\u0000\u0000\u0000[ContentTypes].xmlŖ�N�0\u0010E�|E�M\u0016�q�\u0005B�) \u001eK@�Hl]g�Z�%{",
      "slug": "hollow-win",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Done",
      "journal": "Journal of Economic Perspectives",
      "ssrnUrl": null,
      "webPath": "/papers/fw-hollow-win/",
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 96,
      "name": "Regulatory Convergence: Independent Discovery of Governance Documentation Standards",
      "slug": "da-2",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Done",
      "journal": "Journal of Law, Economics, and Organization",
      "ssrnUrl": null,
      "webPath": "/papers/da-2/",
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 97,
      "name": "Behavioral Properties of Governance Documentation: From Nudge to Guardrail",
      "slug": "da-3",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Done",
      "journal": "Regulation and Governance",
      "ssrnUrl": null,
      "webPath": "/papers/da-3/",
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 98,
      "name": "The Decision Record Chain Standard: Technical Specification and Research Agenda",
      "slug": "da-4",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Done",
      "journal": "Management Science",
      "ssrnUrl": null,
      "webPath": "/papers/da-4/",
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 99,
      "name": "The Decision Record & Control Standard: An Open-Source Specification for Multi-Principal Governance Architecture",
      "slug": "da-5",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Done",
      "journal": "Journal of Economic Theory",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 100,
      "name": "The Jurisdictional Arbitrage Floor Theorem: How Sovereign Competition Creates an Irreducible Welfare Cost",
      "slug": "jurisdictional-arbitrage-floor",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Drafting",
      "journal": "Journal of International Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 101,
      "name": "The Fiscal Capture Universality Theorem: When Government Revenue Dependency Blocks Structural Reform",
      "slug": "fiscal-capture-universality",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Drafting",
      "journal": "Journal of Public Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 102,
      "name": "The General Ratchet Impossibility Theorem: Why Welfare-Destroying Processes Resist Reversal",
      "slug": "general-ratchet-impossibility",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Drafting",
      "journal": "Journal of Economic Theory",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 103,
      "name": "The Constitutive Identity Impossibility Theorem: Why Populations Resist Reforms That Would Make Them Better Off",
      "slug": "constitutive-identity-impossibility",
      "kind": "Foundational",
      "category": "Foundational",
      "status": "Drafting",
      "journal": "Journal of Economic Theory",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 104,
      "name": "Automation-Driven Institutional Decay: A General Theorem",
      "slug": "acemoglu-automation-institutional-decay",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of the European Economic Association",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 105,
      "name": "The Structural Bridge: A Unified Decomposition of Local Average Treatment Effects into Interpretable Economic Primitives",
      "slug": "angrist-structural-bridge",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Review of Economics and Statistics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 106,
      "name": "A Welfare Completion Theorem for Global Value Chains: Bilateral Contracts, Node Externalities, and the Community the Make-or-Buy Decision Cannot Price",
      "slug": "antras-gvc-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of International Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 107,
      "name": "The Third-Party Welfare Theorem of Predictable Irrationality: When Bilateral Consumer Bias Systematically Destroys Non-Participant Welfare",
      "slug": "ariely-predictable-irrationality",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Economic Behavior & Organization",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 108,
      "name": "Auctions with Third-Party Welfare: A General Framework",
      "slug": "auctions-third-party",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Economic Theory",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 109,
      "name": "The Technology Adoption Externality: A Welfare Theorem for Routine-Biased Technical Change",
      "slug": "autor-labor-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Quarterly Journal of Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 110,
      "name": "The Information-Environment Welfare Theorem: Accounting Regime Choice as a Three-Class Welfare Allocation",
      "slug": "ball-accounting-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Accounting and Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 111,
      "name": "A Unified Behavioral Asset-Pricing Model: Prospect Theory, Extrapolation, and Sentiment in General Equilibrium",
      "slug": "barberis-behavioral-asset-pricing",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Review of Financial Studies",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 112,
      "name": "Sustained Competitive Advantage as Hollow Win: A Welfare-Theoretic Extension of the Resource-Based View",
      "slug": "barney-rbv-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Strategic Management Journal",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 113,
      "name": "The Institutional-Precondition Welfare Theorem",
      "slug": "black-legacy-corporate-law",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Corporation Law",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 114,
      "name": "The Structural-Hole Welfare Theorem: When Brokerage Extracts from the Disconnected Community",
      "slug": "burt-structural-holes",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "American Journal of Sociology",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 115,
      "name": "The Structural-Hole Welfare Theorem: When Brokerage Extracts from the Disconnected Community",
      "slug": "burt-structural-holes-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Administrative Science Quarterly",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 116,
      "name": "The Calabresian Third-Party Welfare Theorem: Rule Choice, Accident Cost Allocation, and the System Welfare Gap",
      "slug": "calabresi-tort-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Yale Law Journal",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 117,
      "name": "Technology Welfare Completion: When Bilateral Value-of-Life Accounting Misses the System That Produces the Innovation",
      "slug": "cutler-technology-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Health Affairs",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 118,
      "name": "The Earnings-Quality Welfare Theorem: When the Privately Efficient Earnings Signal Diverges from the Socially Efficient One",
      "slug": "dechow-earnings-quality",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "The Accounting Review",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 119,
      "name": "The Welfare Cost of Expert Forecast Error: A Forecast Welfare Loss Theorem Extending DellaVigna's Forecast-Accuracy Program",
      "slug": "dellavigna-forecast-meta",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Economic Literature",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 120,
      "name": "When Isomorphism Destroys Welfare: A Formal Theorem for Institutional Convergence",
      "slug": "dimaggio-powell-institutional-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "American Sociological Review",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 121,
      "name": "Corporate Law as Default Contract: The Unfinished Coasean Theorem",
      "slug": "easterbrook-corporate-default",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Law, Economics, and Organization",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 122,
      "name": "The Efficient Markets Welfare Exclusion Theorem: Informational Efficiency, Allocative Welfare, and the Price of Everything Except the Cost",
      "slug": "fama-efficient-markets-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Portfolio Management",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 123,
      "name": "A Disciplined Cross-Section: Bayesian Model Averaging over the Factor Zoo Under the Joint-Hypothesis Constraint",
      "slug": "fama-factor-zoo",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Review of Financial Studies",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 124,
      "name": "When Embeddedness Helps and When It Harms: A Welfare Theorem for Social Structure in Markets",
      "slug": "granovetter-embeddedness-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "American Journal of Sociology",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 125,
      "name": "The Incomplete Contracts Welfare Theorem: Residual Discretion, Asymmetric Incompleteness, and the Third-Party Cost of Unwritten Terms",
      "slug": "grossman-hart-incomplete-contracts",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Law and Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 126,
      "name": "Upper Echelons and Third-Party Welfare: A Formal Theorem Linking TMT Cognitive Composition to System Outcomes",
      "slug": "hambrick-upper-echelons",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Academy of Management Review",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 127,
      "name": "The Welfare Conditions of Ownership Form: A General Theorem",
      "slug": "hansmann-ownership-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Law, Economics, and Organization",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 128,
      "name": "The Epistemic Boundary Theorem: Completing Hayek's Knowledge Argument for System Welfare",
      "slug": "hayek-legacy-knowledge-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Economic Literature",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 129,
      "name": "The Voluntary Disclosure Welfare Theorem: When Corporate Communication Cannot Close the Information Asymmetry Welfare Gap",
      "slug": "healy-palepu",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Accounting and Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 130,
      "name": "The Disclosure Welfare Theorem: Why Manager-Chosen Disclosure Quality Destroys Welfare for Non-Contracting Parties Unless Enforcement Binds",
      "slug": "healy-palepu-earnings-management",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "The Accounting Review",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 131,
      "name": "The GVC Hollow Win Theorem: System Welfare Under Global Value Chain Optimization",
      "slug": "helpman-trade-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Quarterly Journal of Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 132,
      "name": "The Information-Insensitivity Welfare Theorem: When Designed Opacity Becomes Crisis-Time Welfare Destruction",
      "slug": "holmstrom",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Review of Economic Studies",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 133,
      "name": "The Antitrust Welfare Standard Completion Theorem: Consumer Welfare as a Subspace of Total Welfare, and the Doctrinal Instruments That Close the Gap",
      "slug": "hovenkamp-antitrust-welfare-standard",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "University of Pennsylvania Law Review",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 134,
      "name": "Agency Costs Under Third-Party Welfare: A Structural Completion of the Jensen-Meckling Program",
      "slug": "jensen-integrity-agency",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Corporate Finance",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 135,
      "name": "Prospect-Theoretic Welfare: The Third-Party Costs of Cognitive Bias — A Tribute to Daniel Kahneman (1934–2024)",
      "slug": "kahneman-legacy-tribute",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Economic Literature",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 136,
      "name": "The Monopsony Welfare Theorem: System Costs of Bilateral Wage Determination",
      "slug": "katz-wage-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Quarterly Journal of Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 137,
      "name": "Bilateral Elegance, System Silence: A Welfare Completion Theorem for Venture Capital Governance",
      "slug": "lerner-venture-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Review of Financial Studies",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 138,
      "name": "Visceral Welfare Economics: Which Self's Utility Counts When States Shift?",
      "slug": "loewenstein-visceral-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Organizational Behavior and Human Decision Processes",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 139,
      "name": "The Heterogeneous-Cycle Welfare Theorem: Decomposing the Cost of Business Cycles by Incidence Class, in Tribute to Robert E. Lucas Jr.",
      "slug": "lucas-macro-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Monetary Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 140,
      "name": "When Reputation Stops Bonding: A General Theorem of Reputational Equilibrium Collapse",
      "slug": "macey-reputational-collapse",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Corporation Law",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 141,
      "name": "Exploration, Exploitation, and the Welfare of Those Outside the Room: A Formal Theorem for Organizational Learning",
      "slug": "march-exploration-exploitation",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Organization Science",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 142,
      "name": "The Dynamic-Replication Welfare Theorem: Bilateral Option Pricing, Hedging Externalities, and the System Cost of Arbitrage-Free Markets",
      "slug": "merton-options-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Mathematical Finance",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 143,
      "name": "The Decoupling Welfare Theorem: When Formal Structure Becomes Myth, Intended Beneficiaries Pay",
      "slug": "meyer-rowan-institutional-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "American Journal of Sociology",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 144,
      "name": "Monotone Comparative Statics in Mechanism Design with Externalities: A Unified Framework",
      "slug": "milgrom-mcs-mechanism-design-externalities",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "To be determined",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 145,
      "name": "The Three-Sector Welfare Balance: Formalizing Mintzberg's Unwritten Theorem",
      "slug": "mintzberg-three-sector-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Academy of Management Review",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 146,
      "name": "The Labor Market Welfare Exclusion Theorem: Why the Non-Matched Pool Is Structurally Outside the Bilateral Wage Bargain",
      "slug": "mortensen-legacy-search-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Review of Economic Studies",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 147,
      "name": "Selection Without Welfare: A Formal Theorem for Evolutionary Economics",
      "slug": "nelson-winter-evolutionary-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Economic Behavior & Organization",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 148,
      "name": "The Utilization Welfare Completion Theorem: When Bilateral Cost-Sharing Optimizes Patient-Insurer Welfare and Degrades System Health Capital",
      "slug": "newhouse-insurance-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Health Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 149,
      "name": "The Integrated Assessment Welfare Completion Theorem: Why the Damage Function Cannot Price the Planetary Commons",
      "slug": "nordhaus-climate-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Nature Climate Change",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 150,
      "name": "Retail Investor Welfare Under Attention, Platform Design, and Gamification: A Unified Framework",
      "slug": "odean-retail-investor-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Finance",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 151,
      "name": "The Governance-Form Welfare Theorem: Third-Party Stakeholder Welfare Across Markets, Bureaucracies, and Clans",
      "slug": "ouchi-clan-governance",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Administrative Science Quarterly",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 152,
      "name": "The Matching Welfare Theorem: Why the Beveridge Curve Is Structurally Excluded from the Bilateral Wage Bargain",
      "slug": "pissarides-matching-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Review of Economic Studies",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 153,
      "name": "The Status-Order Welfare Theorem: Self-Reproducing Status Orders, Excluded Classes, and the Divergence of Private and System Welfare",
      "slug": "podolny-status-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "American Journal of Sociology",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 154,
      "name": "The Wealth-Maximization Welfare Theorem: Characterizing When Bilateral Kaldor-Hicks Efficiency Maximizes System Welfare and When It Systematically Destroys It",
      "slug": "posner-law-economics",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Legal Studies",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 155,
      "name": "The Commitment Welfare Theorem: Time-Inconsistency as a Three-Class Welfare Transfer and the Case for Exogenous Commitment",
      "slug": "prescott-time-consistency",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Political Economy",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 156,
      "name": "Reference-Dependent Welfare Under Present Bias: A Unified Framework for Consumption Choice",
      "slug": "rabin-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of the European Economic Association",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 157,
      "name": "The Three-Pillar Governance Theorem: State, Market, and Community as Complements Under Welfare Constraints",
      "slug": "rajan-three-pillars",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Economic Literature",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 158,
      "name": "The Factor-Structure Welfare Theorem: APT, Non-Participant Exposure, and the Price of Systematic Risk Outside the Market",
      "slug": "ross-apt-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Finance",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 159,
      "name": "Private Information and Non-Participant Welfare: A General Impossibility Theorem",
      "slug": "satterthwaite-private-information-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Rand Journal of Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 160,
      "name": "Bilateral Precision, System Blindness: A Welfare Completion Theorem for Merger Review",
      "slug": "shapiro-merger-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Industrial Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 161,
      "name": "The Matching-Mechanism Third-Party Welfare Theorem: Welfare Effects on Non-Matched Participants",
      "slug": "shapley-roth-matching-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Games and Economic Behavior",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 162,
      "name": "A Unified Behavioral Asset Pricing Theorem: Integrating SP/A Preferences, Self-Control, the Disposition Effect, and Sentiment into a Single Equilibrium Kernel",
      "slug": "shefrin-behavioral-asset-pricing",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Financial and Quantitative Analysis",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 163,
      "name": "A Welfare Theorem for Narrative-Driven Asset Markets",
      "slug": "shiller-narrative-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Economic Perspectives",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 164,
      "name": "The Identification-Welfare Theorem: VAR-Identified Shocks, Heterogeneous-Agent Structure, and the Systematic Misstatement of Class-S Welfare in Monetary and Fiscal Policy Analysis",
      "slug": "sims-monetary-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Monetary Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 165,
      "name": "Monetary Policy Under Financial-Stability Constraints: A Unified Welfare Theorem",
      "slug": "stein-monetary-macroprudential-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Financial Intermediation",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 166,
      "name": "Risk Management's Hollow Win: How Corporate Hedging Maximizes Shareholder Value While Degrading Financial System Stability",
      "slug": "stulz-risk-management-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Finance",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 167,
      "name": "Dynamic Capabilities and System Welfare: A General Theorem for When Capability-Based Competitive Advantage Degrades the System That Produced It",
      "slug": "teece-dynamic-capabilities-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Strategic Management Journal",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 168,
      "name": "The Positive Accounting Welfare Theorem: Contracting Costs, Standard-Setting Choices, and the Systematic Exclusion of Third-Party Welfare",
      "slug": "watts-zimmerman-positive-accounting",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "The Accounting Review",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 169,
      "name": "The Sensemaking Welfare Theorem: How Retrospective Attribution Systematically Under-Prices Third-Party Welfare Costs",
      "slug": "weick-sensemaking",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Organization Science",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 170,
      "name": "Tail Welfare Irreducibility: Completing the Dismal Theorem — A Tribute to Martin L. Weitzman",
      "slug": "weitzman-legacy-dismal-theorem",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Review of Economics and Statistics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 171,
      "name": "The Accountability Substitution Theorem: When Foreign Aid Displaces the Fiscal-Bargaining Mechanism That Produces Domestic Political Accountability",
      "slug": "easterly-aid-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "World Development",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 172,
      "name": "The Convexity Premium Welfare Theorem: Greedy Jobs, Temporal Inflexibility, and the Structural Exclusion of Constrained-Worker Welfare",
      "slug": "goldin-gender-earnings-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Quarterly Journal of Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 173,
      "name": "The Venture Capital Welfare Externality Theorem: Carry Structures, Exit Pressure, and the Structural Exclusion of Ecosystem Welfare",
      "slug": "gompers-vc-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Business Venturing",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 174,
      "name": "The Residual Control Welfare Theorem: Incomplete Contracts, Ownership, and the Structural Exclusion of Non-Owner Welfare",
      "slug": "grossman-hart-ownership-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of Law and Economics",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 175,
      "name": "The Innovation Welfare Asymmetry Theorem: Technological Search, Creative Destruction, and the Structural Exclusion of Displacement Welfare",
      "slug": "kortum-innovation-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Research Policy",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 176,
      "name": "The Temporal Self-Exclusion Welfare Theorem: Present Bias, Financial Product Design, and the Structural Exploitation of Future-Self Welfare",
      "slug": "laibson-lifecycle-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Journal of the European Economic Association",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 177,
      "name": "Private Hazard, System Hazard: A Welfare Decomposition for Health Insurance Markets",
      "slug": "pauly-moral-hazard-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Health Affairs",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 178,
      "name": "The Strategic Welfare Isolation Theorem: Competitive Advantage, Isolating Mechanisms, and the Protection of Welfare-Destroying Rents",
      "slug": "rumelt-strategy-welfare",
      "kind": "Scholar",
      "category": "Scholar",
      "status": "Drafting",
      "journal": "Strategic Management Journal",
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null,
      "expectedPubDate": "2027–2028",
      "fallback": null
    },
    {
      "rank": 179,
      "name": "Applying the System Asset Pricing Model to Nuclear Fission: The Persistence Floor and the Welfare Cost of Radioactive Legacy",
      "slug": "nuclear",
      "kind": "Control",
      "category": "Control / Physical",
      "status": "Done",
      "journal": "Energy Policy",
      "ssrnUrl": null,
      "webPath": "/papers/nuclear/",
      "blocker": null,
      "fallback": "Nuclear Engineering and Technology",
      "expectedPubDate": "2027 Q4"
    },
    {
      "rank": 180,
      "name": "Applying the System Asset Pricing Model to Gig Economy Platforms: Measuring the System Welfare Cost of Worker Misclassification",
      "slug": "gig-economy",
      "kind": "Control",
      "category": "Control / Institutional / Legal",
      "status": "Done",
      "journal": "ILR Review",
      "ssrnUrl": null,
      "webPath": "/papers/gig-economy/",
      "blocker": null,
      "fallback": "British Journal of Industrial Relations",
      "expectedPubDate": "2027 Q4"
    }
  ],
  "books": [
    {
      "rank": 1,
      "name": "The Hollow Win",
      "slug": "book-ppt",
      "kind": "Book",
      "category": "Book",
      "status": "Done",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null
    },
    {
      "rank": 2,
      "name": "Prove It: Banking",
      "slug": "book-da-banking",
      "kind": "Book",
      "category": "Book",
      "status": "Done",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null
    },
    {
      "rank": 3,
      "name": "Prove It: Executive",
      "slug": "book-csuite",
      "kind": "Book",
      "category": "Book",
      "status": "Done",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null
    },
    {
      "rank": 5,
      "name": "Prove It: Global",
      "slug": "book-da-global",
      "kind": "Book",
      "category": "Book",
      "status": "Done",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null
    },
    {
      "rank": 6,
      "name": "Decision Accounting",
      "slug": "book-da-textbook",
      "kind": "Book",
      "category": "Book",
      "status": "Done",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null
    },
    {
      "rank": 7,
      "name": "The $86 Trillion Problem",
      "slug": "book-86-trillion",
      "kind": "Book",
      "category": "Book",
      "status": "Drafting",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null
    },
    {
      "rank": 8,
      "name": "The New Goal",
      "slug": "book-new-goal",
      "kind": "Book",
      "category": "Book",
      "status": "Done",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null
    },
    {
      "rank": 9,
      "name": "Who Signs the Paper?",
      "slug": "book-who-signs",
      "kind": "Book",
      "category": "Book",
      "status": "Drafting",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null
    },
    {
      "rank": 10,
      "name": "The Platform Trap",
      "slug": "book-platform",
      "kind": "Book",
      "category": "Book",
      "status": "Drafting",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null
    },
    {
      "rank": 11,
      "name": "The Legitimacy Crisis",
      "slug": "book-legitimacy",
      "kind": "Book",
      "category": "Book",
      "status": "Drafting",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null
    },
    {
      "rank": 12,
      "name": "The Nordic Exception",
      "slug": "book-nordic",
      "kind": "Book",
      "category": "Book",
      "status": "Drafting",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null
    },
    {
      "rank": 13,
      "name": "Fifty-One Dollars",
      "slug": "book-51-dollars",
      "kind": "Book",
      "category": "Book",
      "status": "Drafting",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null
    },
    {
      "rank": 14,
      "name": "The Impossible Twenty-Two",
      "slug": "book-impossible",
      "kind": "Book",
      "category": "Book",
      "status": "Drafting",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": null
    },
    {
      "rank": 15,
      "name": "What Should the Regulator Do?",
      "slug": "book-regulator-do",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 16,
      "name": "The Rule Change",
      "slug": "book-rule-change",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 17,
      "name": "The Regulator's Missing Variable",
      "slug": "book-regulator-missing-variable",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 18,
      "name": "The Jurisdiction Trap",
      "slug": "book-jurisdiction-trap",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 19,
      "name": "Disclosure Is Not Enough",
      "slug": "book-disclosure-not-enough",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 20,
      "name": "The Five-Minute Test",
      "slug": "book-five-minute-test",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 21,
      "name": "The Field 16 State",
      "slug": "book-field-16-state",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 22,
      "name": "The Safety Case for Society",
      "slug": "book-safety-case-society",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 23,
      "name": "Private Rulebooks",
      "slug": "book-private-rulebooks",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 24,
      "name": "The Source of the Rate",
      "slug": "book-source-of-the-rate",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 25,
      "name": "The Capture Ledger",
      "slug": "book-capture-ledger",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 26,
      "name": "The Systems We Forgot to Price",
      "slug": "book-systems-forgot-price",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 27,
      "name": "The Price They All Use",
      "slug": "book-price-they-all-use",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 28,
      "name": "The Operations of Trust",
      "slug": "book-operations-of-trust",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 29,
      "name": "After Consent",
      "slug": "book-after-consent",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 30,
      "name": "The Accountability Machine",
      "slug": "book-accountability-machine",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    },
    {
      "rank": 31,
      "name": "The Reason Was Not Recorded",
      "slug": "book-reason-not-recorded",
      "kind": "Book Candidate",
      "category": "Book Candidate",
      "status": "Not Started",
      "journal": null,
      "ssrnUrl": null,
      "webPath": null,
      "blocker": "Needs source package and outline"
    }
  ]
};
